// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StatusGizi.Infrastructure.Database;

#nullable disable

namespace StatusGizi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241123110944_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.Property<string>("NIK")
                        .HasColumnType("text");

                    b.Property<double>("BeratBadanWaktuLahir")
                        .HasColumnType("double precision");

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrangTuaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalLahir")
                        .HasColumnType("date");

                    b.Property<double>("TinggiBadanWaktuLahir")
                        .HasColumnType("double precision");

                    b.HasKey("NIK");

                    b.HasIndex("OrangTuaId");

                    b.ToTable("TblBalita");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.DesaKelurahan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblDesaKelurahan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nama = "Beirafu"
                        },
                        new
                        {
                            Id = 2,
                            Nama = "Berdao"
                        },
                        new
                        {
                            Id = 3,
                            Nama = "Tulamalae"
                        },
                        new
                        {
                            Id = 4,
                            Nama = "Umanen"
                        });
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesaKelurahanId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DesaKelurahanId");

                    b.ToTable("TblOrangTua");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DesaKelurahanId = 1,
                            Nama = "VALENTINUS C.KIIK "
                        },
                        new
                        {
                            Id = 2,
                            DesaKelurahanId = 1,
                            Nama = "VALENTINUS C.KIIK "
                        });
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Pengecekan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BalitaNIK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("BeratBadan")
                        .HasColumnType("double precision");

                    b.Property<int>("KategoriGizi")
                        .HasColumnType("integer");

                    b.Property<double>("LingkarLenganAtas")
                        .HasColumnType("double precision");

                    b.Property<int>("PosyanduId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalPengecekan")
                        .HasColumnType("date");

                    b.Property<double>("TinggiBadan")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BalitaNIK");

                    b.HasIndex("PosyanduId");

                    b.ToTable("TblPengecekan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesaKelurahanId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DesaKelurahanId");

                    b.ToTable("TblPosyandu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DesaKelurahanId = 1,
                            Nama = "Asparagus"
                        },
                        new
                        {
                            Id = 2,
                            DesaKelurahanId = 4,
                            Nama = "BTN"
                        },
                        new
                        {
                            Id = 3,
                            DesaKelurahanId = 4,
                            Nama = "Hali Nurak"
                        },
                        new
                        {
                            Id = 4,
                            DesaKelurahanId = 2,
                            Nama = "Kampung Jati"
                        },
                        new
                        {
                            Id = 5,
                            DesaKelurahanId = 1,
                            Nama = "Ketapang"
                        },
                        new
                        {
                            Id = 6,
                            DesaKelurahanId = 2,
                            Nama = "Madrasah"
                        },
                        new
                        {
                            Id = 7,
                            DesaKelurahanId = 1,
                            Nama = "Melati"
                        },
                        new
                        {
                            Id = 8,
                            DesaKelurahanId = 3,
                            Nama = "Nekafehan"
                        },
                        new
                        {
                            Id = 9,
                            DesaKelurahanId = 4,
                            Nama = "Onoboi"
                        },
                        new
                        {
                            Id = 10,
                            DesaKelurahanId = 1,
                            Nama = "Sedap Malam"
                        },
                        new
                        {
                            Id = 11,
                            DesaKelurahanId = 4,
                            Nama = "Sesekoe A"
                        },
                        new
                        {
                            Id = 12,
                            DesaKelurahanId = 4,
                            Nama = "Sesekoe B"
                        },
                        new
                        {
                            Id = 13,
                            DesaKelurahanId = 2,
                            Nama = "Tatakiren"
                        },
                        new
                        {
                            Id = 14,
                            DesaKelurahanId = 3,
                            Nama = "Toro"
                        },
                        new
                        {
                            Id = 15,
                            DesaKelurahanId = 3,
                            Nama = "Tulamalae 1"
                        },
                        new
                        {
                            Id = 16,
                            DesaKelurahanId = 3,
                            Nama = "Tulamalae 2"
                        },
                        new
                        {
                            Id = 17,
                            DesaKelurahanId = 4,
                            Nama = "Wekatimun 1"
                        },
                        new
                        {
                            Id = 18,
                            DesaKelurahanId = 4,
                            Nama = "Wekatimun 2"
                        },
                        new
                        {
                            Id = 19,
                            DesaKelurahanId = 4,
                            Nama = "Wekatimun 3"
                        });
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.StandarBeratMenurutBBTB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("integer");

                    b.Property<int>("KategoriUmur")
                        .HasColumnType("integer");

                    b.Property<double>("MedianBeratBadan")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus1")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus2")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus3")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus1")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus2")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus3")
                        .HasColumnType("double precision");

                    b.Property<double>("TinggiBadan")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TblStandarBeratMenurutBBTB");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.OrangTua", "OrangTua")
                        .WithMany("DaftarBalita")
                        .HasForeignKey("OrangTuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrangTua");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.DesaKelurahan", "DesaKelurahan")
                        .WithMany("DaftarOrangTua")
                        .HasForeignKey("DesaKelurahanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesaKelurahan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Pengecekan", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.Balita", "Balita")
                        .WithMany("DaftarPengecekan")
                        .HasForeignKey("BalitaNIK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatusGizi.Domain.Entities.Posyandu", "Posyandu")
                        .WithMany("DaftarPengecekan")
                        .HasForeignKey("PosyanduId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balita");

                    b.Navigation("Posyandu");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.DesaKelurahan", "DesaKelurahan")
                        .WithMany("DaftarPosyandu")
                        .HasForeignKey("DesaKelurahanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesaKelurahan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.Navigation("DaftarPengecekan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.DesaKelurahan", b =>
                {
                    b.Navigation("DaftarOrangTua");

                    b.Navigation("DaftarPosyandu");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.Navigation("DaftarBalita");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.Navigation("DaftarPengecekan");
                });
#pragma warning restore 612, 618
        }
    }
}
