// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StatusGizi.Infrastructure.Database;

#nullable disable

namespace StatusGizi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241124035042_SeedingData6")]
    partial class SeedingData6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.Property<string>("NIK")
                        .HasColumnType("text");

                    b.Property<double>("BeratBadanWaktuLahir")
                        .HasColumnType("double precision");

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrangTuaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalLahir")
                        .HasColumnType("date");

                    b.Property<double>("TinggiBadanWaktuLahir")
                        .HasColumnType("double precision");

                    b.HasKey("NIK");

                    b.HasIndex("OrangTuaId");

                    b.ToTable("TblBalita");

                    b.HasData(
                        new
                        {
                            NIK = "5306611607227754",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "LEANDREY C.KIIK",
                            OrangTuaId = 1,
                            TanggalLahir = new DateOnly(2022, 7, 16),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306610207221488",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "LEANDER CHESTER ANDRADA",
                            OrangTuaId = 2,
                            TanggalLahir = new DateOnly(2022, 7, 2),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306612306228330",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "RAFLY JALEXA",
                            OrangTuaId = 3,
                            TanggalLahir = new DateOnly(2022, 6, 23),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306612109211986",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "SAMUEL A. LEKY",
                            OrangTuaId = 4,
                            TanggalLahir = new DateOnly(2021, 9, 21),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306613009216892",
                            BeratBadanWaktuLahir = 3.1000000000000001,
                            JenisKelamin = 0,
                            Nama = "DERIL TAMPANI",
                            OrangTuaId = 5,
                            TanggalLahir = new DateOnly(2021, 9, 30),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306611509215054",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "GAMALIEL DAVIN LAHERA",
                            OrangTuaId = 6,
                            TanggalLahir = new DateOnly(2021, 9, 15),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306611608216534",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "AGUSTINUS I. NITBANI",
                            OrangTuaId = 7,
                            TanggalLahir = new DateOnly(2021, 8, 16),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306611708211553",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "DIRGARIUS A.TANEO",
                            OrangTuaId = 8,
                            TanggalLahir = new DateOnly(2021, 8, 17),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306611506221514",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "KHAMALIK SAVERIO",
                            OrangTuaId = 9,
                            TanggalLahir = new DateOnly(2022, 6, 15),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306612705226233",
                            BeratBadanWaktuLahir = 3.2000000000000002,
                            JenisKelamin = 0,
                            Nama = "MUH. SYAHKIRULLAH ALGHANI",
                            OrangTuaId = 10,
                            TanggalLahir = new DateOnly(2022, 5, 27),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306612105226289",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "FARHAN ZAKY",
                            OrangTuaId = 11,
                            TanggalLahir = new DateOnly(2022, 5, 21),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306610606224235",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "SEAN",
                            OrangTuaId = 12,
                            TanggalLahir = new DateOnly(2022, 6, 6),
                            TinggiBadanWaktuLahir = 46.0
                        },
                        new
                        {
                            NIK = "5306611505225327",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "MEIDA AMELIA Y FAOT",
                            OrangTuaId = 13,
                            TanggalLahir = new DateOnly(2022, 6, 6),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306611807227328",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "ADRIELO HABU PAH",
                            OrangTuaId = 35,
                            TanggalLahir = new DateOnly(2022, 7, 18),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306610310212700",
                            BeratBadanWaktuLahir = 2.8999999999999999,
                            JenisKelamin = 0,
                            Nama = "GIRLAND WADU",
                            OrangTuaId = 36,
                            TanggalLahir = new DateOnly(2022, 10, 3),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306612608217549",
                            BeratBadanWaktuLahir = 3.3999999999999999,
                            JenisKelamin = 0,
                            Nama = "AGUSTINUS H. PRAWIRA",
                            OrangTuaId = 37,
                            TanggalLahir = new DateOnly(2021, 8, 26),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306611808214604",
                            BeratBadanWaktuLahir = 2.7999999999999998,
                            JenisKelamin = 0,
                            Nama = "ABIMAE AMALO",
                            OrangTuaId = 38,
                            TanggalLahir = new DateOnly(2021, 8, 18),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306611008217236",
                            BeratBadanWaktuLahir = 2.8999999999999999,
                            JenisKelamin = 0,
                            Nama = "AGUS R. BEREMEO",
                            OrangTuaId = 39,
                            TanggalLahir = new DateOnly(2022, 8, 10),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306612804228187",
                            BeratBadanWaktuLahir = 3.1000000000000001,
                            JenisKelamin = 0,
                            Nama = "KRISTIAN PARERA",
                            OrangTuaId = 40,
                            TanggalLahir = new DateOnly(2022, 4, 28),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306612404221654",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "ALEXANDRIO Z. KEFI",
                            OrangTuaId = 41,
                            TanggalLahir = new DateOnly(2022, 4, 24),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306610805228603",
                            BeratBadanWaktuLahir = 2.6000000000000001,
                            JenisKelamin = 0,
                            Nama = "ARSENIUS NAHAK",
                            OrangTuaId = 42,
                            TanggalLahir = new DateOnly(2022, 5, 8),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306610305228386",
                            BeratBadanWaktuLahir = 2.7999999999999998,
                            JenisKelamin = 0,
                            Nama = "MUHAMAD ARHAM SYAKAL",
                            OrangTuaId = 43,
                            TanggalLahir = new DateOnly(2022, 5, 3),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306611503229344",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "CANELO ALVARES MANEK",
                            OrangTuaId = 44,
                            TanggalLahir = new DateOnly(2022, 3, 15),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306611607222447",
                            BeratBadanWaktuLahir = 2.6000000000000001,
                            JenisKelamin = 0,
                            Nama = "ALEXSIUS EL KAPITAN",
                            OrangTuaId = 46,
                            TanggalLahir = new DateOnly(2022, 7, 16),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306611106228326",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "VASCO PEREIRA REIS",
                            OrangTuaId = 47,
                            TanggalLahir = new DateOnly(2022, 6, 11),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306610807221629",
                            BeratBadanWaktuLahir = 3.2000000000000002,
                            JenisKelamin = 0,
                            Nama = "DANTE A. BESSIE",
                            OrangTuaId = 48,
                            TanggalLahir = new DateOnly(2022, 7, 8),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306611410216937",
                            BeratBadanWaktuLahir = 2.7999999999999998,
                            JenisKelamin = 0,
                            Nama = "KORNELIS D. NAHAK",
                            OrangTuaId = 49,
                            TanggalLahir = new DateOnly(2021, 10, 14),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306612709216413",
                            BeratBadanWaktuLahir = 3.1000000000000001,
                            JenisKelamin = 0,
                            Nama = "ILHAM BAHMID",
                            OrangTuaId = 50,
                            TanggalLahir = new DateOnly(2021, 9, 27),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306611907229365",
                            BeratBadanWaktuLahir = 2.6000000000000001,
                            JenisKelamin = 0,
                            Nama = "GRACIANO LOLOMSAIT",
                            OrangTuaId = 51,
                            TanggalLahir = new DateOnly(2022, 7, 19),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306612807224014",
                            BeratBadanWaktuLahir = 2.6000000000000001,
                            JenisKelamin = 0,
                            Nama = "AGNESIA TIARA SIN MAU",
                            OrangTuaId = 52,
                            TanggalLahir = new DateOnly(2022, 7, 28),
                            TinggiBadanWaktuLahir = 45.0
                        },
                        new
                        {
                            NIK = "5303244310870001",
                            BeratBadanWaktuLahir = 3.1000000000000001,
                            JenisKelamin = 0,
                            Nama = "ALANA FERNANDES",
                            OrangTuaId = 53,
                            TanggalLahir = new DateOnly(2022, 7, 18),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5304214606940004",
                            BeratBadanWaktuLahir = 2.8999999999999999,
                            JenisKelamin = 0,
                            Nama = "ALFIAN E. N",
                            OrangTuaId = 54,
                            TanggalLahir = new DateOnly(2022, 7, 1),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306611706223451",
                            BeratBadanWaktuLahir = 3.5,
                            JenisKelamin = 0,
                            Nama = "GIBRAN M. LY RATU",
                            OrangTuaId = 55,
                            TanggalLahir = new DateOnly(2022, 6, 17),
                            TinggiBadanWaktuLahir = 50.0
                        },
                        new
                        {
                            NIK = "5306612404198011",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 0,
                            Nama = "ARYANTO ENYSIUS FAHIK",
                            OrangTuaId = 56,
                            TanggalLahir = new DateOnly(2019, 4, 24),
                            TinggiBadanWaktuLahir = 48.0
                        },
                        new
                        {
                            NIK = "5306616807201646",
                            BeratBadanWaktuLahir = 3.0,
                            JenisKelamin = 1,
                            Nama = "AGATHA L.F.NAIMUNI",
                            OrangTuaId = 57,
                            TanggalLahir = new DateOnly(2020, 7, 28),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5306611708215871",
                            BeratBadanWaktuLahir = 2.5,
                            JenisKelamin = 0,
                            Nama = "GABRIEL RADINGA",
                            OrangTuaId = 58,
                            TanggalLahir = new DateOnly(2021, 8, 17),
                            TinggiBadanWaktuLahir = 49.0
                        },
                        new
                        {
                            NIK = "5319024912229990",
                            BeratBadanWaktuLahir = 3.2000000000000002,
                            JenisKelamin = 1,
                            Nama = "MELTIADES KEOR",
                            OrangTuaId = 59,
                            TanggalLahir = new DateOnly(2022, 12, 9),
                            TinggiBadanWaktuLahir = 51.0
                        },
                        new
                        {
                            NIK = "5319025103229974",
                            BeratBadanWaktuLahir = 3.2000000000000002,
                            JenisKelamin = 1,
                            Nama = "MARIA Y.T. QUIN",
                            OrangTuaId = 60,
                            TanggalLahir = new DateOnly(2022, 3, 11),
                            TinggiBadanWaktuLahir = 51.0
                        });
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.DesaKelurahan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblDesaKelurahan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nama = "Beirafu"
                        },
                        new
                        {
                            Id = 2,
                            Nama = "Berdao"
                        },
                        new
                        {
                            Id = 3,
                            Nama = "Tulamalae"
                        },
                        new
                        {
                            Id = 4,
                            Nama = "Umanen"
                        },
                        new
                        {
                            Id = 5,
                            Nama = "Bangka Kuleng"
                        },
                        new
                        {
                            Id = 6,
                            Nama = "Bangka Leleng"
                        },
                        new
                        {
                            Id = 7,
                            Nama = "Bangka Pau"
                        },
                        new
                        {
                            Id = 8,
                            Nama = "Bea Waek"
                        },
                        new
                        {
                            Id = 9,
                            Nama = "Compang Wesang"
                        },
                        new
                        {
                            Id = 10,
                            Nama = "Golo Lobos"
                        },
                        new
                        {
                            Id = 11,
                            Nama = "Golo Nderu"
                        },
                        new
                        {
                            Id = 12,
                            Nama = "Golo Rengket"
                        },
                        new
                        {
                            Id = 13,
                            Nama = "Gurung Turi"
                        },
                        new
                        {
                            Id = 14,
                            Nama = "Mando Sawu"
                        },
                        new
                        {
                            Id = 15,
                            Nama = "Nggalak Leleng"
                        },
                        new
                        {
                            Id = 16,
                            Nama = "Pocolia"
                        },
                        new
                        {
                            Id = 17,
                            Nama = "Satar Tesem"
                        });
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesaKelurahanId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DesaKelurahanId");

                    b.ToTable("TblOrangTua");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DesaKelurahanId = 1,
                            Nama = "VALENTINUS C.KIIK"
                        },
                        new
                        {
                            Id = 2,
                            DesaKelurahanId = 1,
                            Nama = "JULIUS S.ANDRADA"
                        },
                        new
                        {
                            Id = 3,
                            DesaKelurahanId = 1,
                            Nama = "ARSILIU NENOBAIS"
                        },
                        new
                        {
                            Id = 4,
                            DesaKelurahanId = 1,
                            Nama = "DAMIANUS LEKY"
                        },
                        new
                        {
                            Id = 5,
                            DesaKelurahanId = 1,
                            Nama = "DEFRI TAMPANI"
                        },
                        new
                        {
                            Id = 6,
                            DesaKelurahanId = 1,
                            Nama = "JULIUS D LAHERA"
                        },
                        new
                        {
                            Id = 7,
                            DesaKelurahanId = 1,
                            Nama = "DELVIANA MORUK"
                        },
                        new
                        {
                            Id = 8,
                            DesaKelurahanId = 1,
                            Nama = "OKTOVIANUS TANEO"
                        },
                        new
                        {
                            Id = 9,
                            DesaKelurahanId = 1,
                            Nama = "MUHAMAD SAVERIO"
                        },
                        new
                        {
                            Id = 10,
                            DesaKelurahanId = 1,
                            Nama = "KHANIFATUL"
                        },
                        new
                        {
                            Id = 11,
                            DesaKelurahanId = 1,
                            Nama = "JASMAN SEO"
                        },
                        new
                        {
                            Id = 12,
                            DesaKelurahanId = 1,
                            Nama = "RONALD"
                        },
                        new
                        {
                            Id = 13,
                            DesaKelurahanId = 1,
                            Nama = "MELKI SEDIK FAOT"
                        },
                        new
                        {
                            Id = 14,
                            DesaKelurahanId = 1,
                            Nama = "YUVEN SERAN"
                        },
                        new
                        {
                            Id = 15,
                            DesaKelurahanId = 1,
                            Nama = "PETRUS KAPITAN"
                        },
                        new
                        {
                            Id = 16,
                            DesaKelurahanId = 1,
                            Nama = "MISDA"
                        },
                        new
                        {
                            Id = 17,
                            DesaKelurahanId = 1,
                            Nama = "ADRIANUS IMPI"
                        },
                        new
                        {
                            Id = 18,
                            DesaKelurahanId = 1,
                            Nama = "GAUDENSIA N. TAEK"
                        },
                        new
                        {
                            Id = 19,
                            DesaKelurahanId = 1,
                            Nama = "NOBERTUS KLAU"
                        },
                        new
                        {
                            Id = 20,
                            DesaKelurahanId = 1,
                            Nama = "MARTINUS TEFLOPO"
                        },
                        new
                        {
                            Id = 21,
                            DesaKelurahanId = 1,
                            Nama = "MUSTOFA"
                        },
                        new
                        {
                            Id = 22,
                            DesaKelurahanId = 1,
                            Nama = "R. PRASONG"
                        },
                        new
                        {
                            Id = 23,
                            DesaKelurahanId = 1,
                            Nama = "HENDRIKUS LAISNESI"
                        },
                        new
                        {
                            Id = 24,
                            DesaKelurahanId = 1,
                            Nama = "ARI PANO"
                        },
                        new
                        {
                            Id = 25,
                            DesaKelurahanId = 1,
                            Nama = "RASID HANNS"
                        },
                        new
                        {
                            Id = 26,
                            DesaKelurahanId = 1,
                            Nama = "JUFRIANUS SERAN"
                        },
                        new
                        {
                            Id = 27,
                            DesaKelurahanId = 1,
                            Nama = "ADRIANUS LOROK"
                        },
                        new
                        {
                            Id = 28,
                            DesaKelurahanId = 1,
                            Nama = "MELFIANUS WALENG"
                        },
                        new
                        {
                            Id = 29,
                            DesaKelurahanId = 1,
                            Nama = "YEREMIA G.KABOSU"
                        },
                        new
                        {
                            Id = 30,
                            DesaKelurahanId = 1,
                            Nama = "JERIKSON E FAOT"
                        },
                        new
                        {
                            Id = 31,
                            DesaKelurahanId = 1,
                            Nama = "APOLINARIS AFEANPAH"
                        },
                        new
                        {
                            Id = 32,
                            DesaKelurahanId = 1,
                            Nama = "LINUS UN ARYANDI"
                        },
                        new
                        {
                            Id = 33,
                            DesaKelurahanId = 1,
                            Nama = "FLAVIANUS A. D. UN"
                        },
                        new
                        {
                            Id = 34,
                            DesaKelurahanId = 1,
                            Nama = "AGUSTINUS TALAN"
                        },
                        new
                        {
                            Id = 35,
                            DesaKelurahanId = 2,
                            Nama = "JAMARIA NAMANG"
                        },
                        new
                        {
                            Id = 36,
                            DesaKelurahanId = 2,
                            Nama = "HARI WADU"
                        },
                        new
                        {
                            Id = 37,
                            DesaKelurahanId = 2,
                            Nama = "PAULUS PRAWIRA"
                        },
                        new
                        {
                            Id = 38,
                            DesaKelurahanId = 2,
                            Nama = "IRFAN AMALO"
                        },
                        new
                        {
                            Id = 39,
                            DesaKelurahanId = 2,
                            Nama = "KARLUS BEREMEO"
                        },
                        new
                        {
                            Id = 40,
                            DesaKelurahanId = 2,
                            Nama = "JISMA"
                        },
                        new
                        {
                            Id = 41,
                            DesaKelurahanId = 2,
                            Nama = "ERLIN KAMLASI"
                        },
                        new
                        {
                            Id = 42,
                            DesaKelurahanId = 2,
                            Nama = "DIONISIUS NAHAK"
                        },
                        new
                        {
                            Id = 43,
                            DesaKelurahanId = 2,
                            Nama = "SAHRUDIN"
                        },
                        new
                        {
                            Id = 44,
                            DesaKelurahanId = 2,
                            Nama = "RANDI MANEK"
                        },
                        new
                        {
                            Id = 45,
                            DesaKelurahanId = 2,
                            Nama = "SAVER TAEK"
                        },
                        new
                        {
                            Id = 46,
                            DesaKelurahanId = 3,
                            Nama = "AGAPITUS UN"
                        },
                        new
                        {
                            Id = 47,
                            DesaKelurahanId = 3,
                            Nama = "PEDRO DOS REIS"
                        },
                        new
                        {
                            Id = 48,
                            DesaKelurahanId = 3,
                            Nama = "ALFRED BESSIE"
                        },
                        new
                        {
                            Id = 49,
                            DesaKelurahanId = 3,
                            Nama = "JHON NAHAK"
                        },
                        new
                        {
                            Id = 50,
                            DesaKelurahanId = 3,
                            Nama = "AMINUDIN"
                        },
                        new
                        {
                            Id = 51,
                            DesaKelurahanId = 4,
                            Nama = "GERFAS LOLOMSAIT"
                        },
                        new
                        {
                            Id = 52,
                            DesaKelurahanId = 4,
                            Nama = ""
                        },
                        new
                        {
                            Id = 53,
                            DesaKelurahanId = 4,
                            Nama = "YOHANES KENJAM"
                        },
                        new
                        {
                            Id = 54,
                            DesaKelurahanId = 4,
                            Nama = "MANUEL N"
                        },
                        new
                        {
                            Id = 55,
                            DesaKelurahanId = 4,
                            Nama = "SONNY LY RAU"
                        },
                        new
                        {
                            Id = 56,
                            DesaKelurahanId = 3,
                            Nama = "YOHANES FAHIK"
                        },
                        new
                        {
                            Id = 57,
                            DesaKelurahanId = 4,
                            Nama = "STEFANUS NAIMUNI"
                        },
                        new
                        {
                            Id = 58,
                            DesaKelurahanId = 3,
                            Nama = "MARIA A. SEKAB"
                        },
                        new
                        {
                            Id = 59,
                            DesaKelurahanId = 14,
                            Nama = "BONEFASIUS KEOR"
                        },
                        new
                        {
                            Id = 60,
                            DesaKelurahanId = 13,
                            Nama = "ELFRIDA NDIMUN"
                        });
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Pengecekan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BalitaNIK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("BeratBadan")
                        .HasColumnType("double precision");

                    b.Property<int>("KategoriGizi")
                        .HasColumnType("integer");

                    b.Property<double>("LingkarLenganAtas")
                        .HasColumnType("double precision");

                    b.Property<int>("PosyanduId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalPengecekan")
                        .HasColumnType("date");

                    b.Property<double>("TinggiBadan")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BalitaNIK");

                    b.HasIndex("PosyanduId");

                    b.ToTable("TblPengecekan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BalitaNIK = "5306611607227754",
                            BeratBadan = 5.2999999999999998,
                            KategoriGizi = 5,
                            LingkarLenganAtas = 13.0,
                            PosyanduId = 1,
                            TanggalPengecekan = new DateOnly(2022, 8, 15),
                            TinggiBadan = 52.899999999999999
                        },
                        new
                        {
                            Id = 2,
                            BalitaNIK = "5306610207221488",
                            BeratBadan = 4.0999999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 11.800000000000001,
                            PosyanduId = 1,
                            TanggalPengecekan = new DateOnly(2022, 8, 15),
                            TinggiBadan = 52.700000000000003
                        },
                        new
                        {
                            Id = 3,
                            BalitaNIK = "5306612306228330",
                            BeratBadan = 5.0999999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 11.5,
                            PosyanduId = 1,
                            TanggalPengecekan = new DateOnly(2022, 8, 15),
                            TinggiBadan = 57.200000000000003
                        },
                        new
                        {
                            Id = 4,
                            BalitaNIK = "5306612109211986",
                            BeratBadan = 8.4000000000000004,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 15.0,
                            PosyanduId = 10,
                            TanggalPengecekan = new DateOnly(2022, 8, 8),
                            TinggiBadan = 71.400000000000006
                        },
                        new
                        {
                            Id = 5,
                            BalitaNIK = "5306613009216892",
                            BeratBadan = 8.4499999999999993,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 13.5,
                            PosyanduId = 10,
                            TanggalPengecekan = new DateOnly(2022, 8, 8),
                            TinggiBadan = 72.900000000000006
                        },
                        new
                        {
                            Id = 6,
                            BalitaNIK = "5306611509215054",
                            BeratBadan = 8.4000000000000004,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 14.0,
                            PosyanduId = 7,
                            TanggalPengecekan = new DateOnly(2022, 8, 18),
                            TinggiBadan = 72.099999999999994
                        },
                        new
                        {
                            Id = 7,
                            BalitaNIK = "5306611608216534",
                            BeratBadan = 9.5999999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 14.199999999999999,
                            PosyanduId = 10,
                            TanggalPengecekan = new DateOnly(2022, 8, 8),
                            TinggiBadan = 76.200000000000003
                        },
                        new
                        {
                            Id = 8,
                            BalitaNIK = "5306611708211553",
                            BeratBadan = 8.0,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 12.4,
                            PosyanduId = 1,
                            TanggalPengecekan = new DateOnly(2022, 8, 15),
                            TinggiBadan = 72.0
                        },
                        new
                        {
                            Id = 9,
                            BalitaNIK = "5306611506221514",
                            BeratBadan = 5.2000000000000002,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 15.0,
                            PosyanduId = 1,
                            TanggalPengecekan = new DateOnly(2022, 8, 15),
                            TinggiBadan = 55.899999999999999
                        },
                        new
                        {
                            Id = 10,
                            BalitaNIK = "5306612705226233",
                            BeratBadan = 4.8499999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 10,
                            TanggalPengecekan = new DateOnly(2022, 8, 8),
                            TinggiBadan = 57.299999999999997
                        },
                        new
                        {
                            Id = 11,
                            BalitaNIK = "5306612105226289",
                            BeratBadan = 5.2000000000000002,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 14.0,
                            PosyanduId = 10,
                            TanggalPengecekan = new DateOnly(2022, 8, 8),
                            TinggiBadan = 59.200000000000003
                        },
                        new
                        {
                            Id = 12,
                            BalitaNIK = "5306610606224235",
                            BeratBadan = 6.2999999999999998,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 14.0,
                            PosyanduId = 5,
                            TanggalPengecekan = new DateOnly(2022, 8, 12),
                            TinggiBadan = 61.299999999999997
                        },
                        new
                        {
                            Id = 13,
                            BalitaNIK = "5306611505225327",
                            BeratBadan = 5.4000000000000004,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 13.199999999999999,
                            PosyanduId = 1,
                            TanggalPengecekan = new DateOnly(2022, 8, 15),
                            TinggiBadan = 57.700000000000003
                        },
                        new
                        {
                            Id = 14,
                            BalitaNIK = "5306611807227328",
                            BeratBadan = 3.7999999999999998,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 11.699999999999999,
                            PosyanduId = 6,
                            TanggalPengecekan = new DateOnly(2022, 8, 9),
                            TinggiBadan = 52.899999999999999
                        },
                        new
                        {
                            Id = 15,
                            BalitaNIK = "5306610310212700",
                            BeratBadan = 9.0999999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 15.5,
                            PosyanduId = 6,
                            TanggalPengecekan = new DateOnly(2021, 8, 9),
                            TinggiBadan = 71.900000000000006
                        },
                        new
                        {
                            Id = 16,
                            BalitaNIK = "5306612608217549",
                            BeratBadan = 10.699999999999999,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 15.0,
                            PosyanduId = 4,
                            TanggalPengecekan = new DateOnly(2022, 8, 12),
                            TinggiBadan = 78.0
                        },
                        new
                        {
                            Id = 17,
                            BalitaNIK = "5306611808214604",
                            BeratBadan = 8.9000000000000004,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 16.0,
                            PosyanduId = 4,
                            TanggalPengecekan = new DateOnly(2022, 8, 12),
                            TinggiBadan = 71.400000000000006
                        },
                        new
                        {
                            Id = 18,
                            BalitaNIK = "5306611008217236",
                            BeratBadan = 9.5999999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 14.0,
                            PosyanduId = 13,
                            TanggalPengecekan = new DateOnly(2021, 8, 10),
                            TinggiBadan = 82.200000000000003
                        },
                        new
                        {
                            Id = 19,
                            BalitaNIK = "5306612804228187",
                            BeratBadan = 5.5,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 13.0,
                            PosyanduId = 13,
                            TanggalPengecekan = new DateOnly(2022, 8, 10),
                            TinggiBadan = 60.899999999999999
                        },
                        new
                        {
                            Id = 20,
                            BalitaNIK = "5306612404221654",
                            BeratBadan = 5.25,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 12.5,
                            PosyanduId = 13,
                            TanggalPengecekan = new DateOnly(2022, 8, 10),
                            TinggiBadan = 59.200000000000003
                        },
                        new
                        {
                            Id = 21,
                            BalitaNIK = "5306610805228603",
                            BeratBadan = 5.5999999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 4,
                            TanggalPengecekan = new DateOnly(2022, 8, 12),
                            TinggiBadan = 58.200000000000003
                        },
                        new
                        {
                            Id = 22,
                            BalitaNIK = "5306610305228386",
                            BeratBadan = 5.7000000000000002,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 4,
                            TanggalPengecekan = new DateOnly(2022, 8, 12),
                            TinggiBadan = 61.200000000000003
                        },
                        new
                        {
                            Id = 23,
                            BalitaNIK = "5306611503229344",
                            BeratBadan = 6.7000000000000002,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 14.5,
                            PosyanduId = 4,
                            TanggalPengecekan = new DateOnly(2022, 8, 12),
                            TinggiBadan = 63.0
                        },
                        new
                        {
                            Id = 24,
                            BalitaNIK = "5306611607222447",
                            BeratBadan = 4.2000000000000002,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 16,
                            TanggalPengecekan = new DateOnly(2022, 8, 11),
                            TinggiBadan = 53.5
                        },
                        new
                        {
                            Id = 25,
                            BalitaNIK = "5306611106228326",
                            BeratBadan = 6.2999999999999998,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 14,
                            TanggalPengecekan = new DateOnly(2022, 8, 8),
                            TinggiBadan = 63.0
                        },
                        new
                        {
                            Id = 26,
                            BalitaNIK = "5306610807221629",
                            BeratBadan = 4.7999999999999998,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 16,
                            TanggalPengecekan = new DateOnly(2022, 8, 11),
                            TinggiBadan = 58.5
                        },
                        new
                        {
                            Id = 27,
                            BalitaNIK = "5306611410216937",
                            BeratBadan = 7.5,
                            KategoriGizi = 1,
                            LingkarLenganAtas = 12.5,
                            PosyanduId = 8,
                            TanggalPengecekan = new DateOnly(2021, 8, 16),
                            TinggiBadan = 71.799999999999997
                        },
                        new
                        {
                            Id = 28,
                            BalitaNIK = "5306612709216413",
                            BeratBadan = 9.4000000000000004,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 14.5,
                            PosyanduId = 15,
                            TanggalPengecekan = new DateOnly(2021, 8, 12),
                            TinggiBadan = 72.299999999999997
                        },
                        new
                        {
                            Id = 29,
                            BalitaNIK = "5306611907229365",
                            BeratBadan = 4.7000000000000002,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 17,
                            TanggalPengecekan = new DateOnly(2022, 8, 5),
                            TinggiBadan = 57.0
                        },
                        new
                        {
                            Id = 30,
                            BalitaNIK = "5306612807224014",
                            BeratBadan = 3.6000000000000001,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 9,
                            TanggalPengecekan = new DateOnly(2022, 8, 19),
                            TinggiBadan = 51.0
                        },
                        new
                        {
                            Id = 31,
                            BalitaNIK = "5303244310870001",
                            BeratBadan = 4.0999999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 12,
                            TanggalPengecekan = new DateOnly(2022, 8, 18),
                            TinggiBadan = 53.200000000000003
                        },
                        new
                        {
                            Id = 32,
                            BalitaNIK = "5304214606940004",
                            BeratBadan = 4.2999999999999998,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 12,
                            TanggalPengecekan = new DateOnly(2022, 8, 18),
                            TinggiBadan = 53.399999999999999
                        },
                        new
                        {
                            Id = 33,
                            BalitaNIK = "5306611706223451",
                            BeratBadan = 5.0999999999999996,
                            KategoriGizi = 2,
                            LingkarLenganAtas = 0.0,
                            PosyanduId = 17,
                            TanggalPengecekan = new DateOnly(2022, 8, 5),
                            TinggiBadan = 55.799999999999997
                        },
                        new
                        {
                            Id = 34,
                            BalitaNIK = "5306612404198011",
                            BeratBadan = 9.0,
                            KategoriGizi = 0,
                            LingkarLenganAtas = 14.0,
                            PosyanduId = 16,
                            TanggalPengecekan = new DateOnly(2022, 8, 11),
                            TinggiBadan = 88.0
                        },
                        new
                        {
                            Id = 35,
                            BalitaNIK = "5306616807201646",
                            BeratBadan = 7.2999999999999998,
                            KategoriGizi = 0,
                            LingkarLenganAtas = 13.0,
                            PosyanduId = 19,
                            TanggalPengecekan = new DateOnly(2022, 8, 12),
                            TinggiBadan = 77.0
                        },
                        new
                        {
                            Id = 36,
                            BalitaNIK = "5306611708215871",
                            BeratBadan = 6.2000000000000002,
                            KategoriGizi = 0,
                            LingkarLenganAtas = 13.0,
                            PosyanduId = 15,
                            TanggalPengecekan = new DateOnly(2022, 8, 12),
                            TinggiBadan = 71.200000000000003
                        },
                        new
                        {
                            Id = 37,
                            BalitaNIK = "5319024912229990",
                            BeratBadan = 3.3999999999999999,
                            KategoriGizi = 0,
                            LingkarLenganAtas = 10.5,
                            PosyanduId = 40,
                            TanggalPengecekan = new DateOnly(2022, 12, 9),
                            TinggiBadan = 59.899999999999999
                        },
                        new
                        {
                            Id = 38,
                            BalitaNIK = "5319025103229974",
                            BeratBadan = 6.7999999999999998,
                            KategoriGizi = 0,
                            LingkarLenganAtas = 13.699999999999999,
                            PosyanduId = 36,
                            TanggalPengecekan = new DateOnly(2022, 3, 11),
                            TinggiBadan = 75.900000000000006
                        });
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesaKelurahanId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DesaKelurahanId");

                    b.ToTable("TblPosyandu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DesaKelurahanId = 1,
                            Nama = "Asparagus"
                        },
                        new
                        {
                            Id = 2,
                            DesaKelurahanId = 4,
                            Nama = "BTN"
                        },
                        new
                        {
                            Id = 3,
                            DesaKelurahanId = 4,
                            Nama = "Hali Nurak"
                        },
                        new
                        {
                            Id = 4,
                            DesaKelurahanId = 2,
                            Nama = "Kampung Jati"
                        },
                        new
                        {
                            Id = 5,
                            DesaKelurahanId = 1,
                            Nama = "Ketapang"
                        },
                        new
                        {
                            Id = 6,
                            DesaKelurahanId = 2,
                            Nama = "Madrasah"
                        },
                        new
                        {
                            Id = 7,
                            DesaKelurahanId = 1,
                            Nama = "Melati"
                        },
                        new
                        {
                            Id = 8,
                            DesaKelurahanId = 3,
                            Nama = "Nekafehan"
                        },
                        new
                        {
                            Id = 9,
                            DesaKelurahanId = 4,
                            Nama = "Onoboi"
                        },
                        new
                        {
                            Id = 10,
                            DesaKelurahanId = 1,
                            Nama = "Sedap Malam"
                        },
                        new
                        {
                            Id = 11,
                            DesaKelurahanId = 4,
                            Nama = "Sesekoe A"
                        },
                        new
                        {
                            Id = 12,
                            DesaKelurahanId = 4,
                            Nama = "Sesekoe B"
                        },
                        new
                        {
                            Id = 13,
                            DesaKelurahanId = 2,
                            Nama = "Tatakiren"
                        },
                        new
                        {
                            Id = 14,
                            DesaKelurahanId = 3,
                            Nama = "Toro"
                        },
                        new
                        {
                            Id = 15,
                            DesaKelurahanId = 3,
                            Nama = "Tulamalae 1"
                        },
                        new
                        {
                            Id = 16,
                            DesaKelurahanId = 3,
                            Nama = "Tulamalae 2"
                        },
                        new
                        {
                            Id = 17,
                            DesaKelurahanId = 4,
                            Nama = "Wekatimun 1"
                        },
                        new
                        {
                            Id = 18,
                            DesaKelurahanId = 4,
                            Nama = "Wekatimun 2"
                        },
                        new
                        {
                            Id = 19,
                            DesaKelurahanId = 4,
                            Nama = "Wekatimun 3"
                        },
                        new
                        {
                            Id = 20,
                            DesaKelurahanId = 7,
                            Nama = "Bealing 1"
                        },
                        new
                        {
                            Id = 21,
                            DesaKelurahanId = 7,
                            Nama = "Bealing 2"
                        },
                        new
                        {
                            Id = 22,
                            DesaKelurahanId = 7,
                            Nama = "Bealing 2"
                        },
                        new
                        {
                            Id = 23,
                            DesaKelurahanId = 5,
                            Nama = "Leci"
                        },
                        new
                        {
                            Id = 24,
                            DesaKelurahanId = 6,
                            Nama = "Ceka Likang"
                        },
                        new
                        {
                            Id = 25,
                            DesaKelurahanId = 6,
                            Nama = "Golo Tenda"
                        },
                        new
                        {
                            Id = 26,
                            DesaKelurahanId = 8,
                            Nama = "Carang"
                        },
                        new
                        {
                            Id = 27,
                            DesaKelurahanId = 9,
                            Nama = "Geleng"
                        },
                        new
                        {
                            Id = 28,
                            DesaKelurahanId = 9,
                            Nama = "Golo Ara"
                        },
                        new
                        {
                            Id = 29,
                            DesaKelurahanId = 9,
                            Nama = "Wesang"
                        },
                        new
                        {
                            Id = 30,
                            DesaKelurahanId = 10,
                            Nama = "Lame 2"
                        },
                        new
                        {
                            Id = 31,
                            DesaKelurahanId = 10,
                            Nama = "Pelus"
                        },
                        new
                        {
                            Id = 32,
                            DesaKelurahanId = 11,
                            Nama = "Lamba"
                        },
                        new
                        {
                            Id = 33,
                            DesaKelurahanId = 11,
                            Nama = "Nderu"
                        },
                        new
                        {
                            Id = 34,
                            DesaKelurahanId = 11,
                            Nama = "Nggari"
                        },
                        new
                        {
                            Id = 35,
                            DesaKelurahanId = 12,
                            Nama = "Majung"
                        },
                        new
                        {
                            Id = 36,
                            DesaKelurahanId = 13,
                            Nama = "Ncuang"
                        },
                        new
                        {
                            Id = 37,
                            DesaKelurahanId = 13,
                            Nama = "Ndueng"
                        },
                        new
                        {
                            Id = 38,
                            DesaKelurahanId = 13,
                            Nama = "Nengkal"
                        },
                        new
                        {
                            Id = 39,
                            DesaKelurahanId = 13,
                            Nama = "Pocong"
                        },
                        new
                        {
                            Id = 40,
                            DesaKelurahanId = 14,
                            Nama = "Benteng Dima"
                        },
                        new
                        {
                            Id = 41,
                            DesaKelurahanId = 14,
                            Nama = "Golo Laci"
                        },
                        new
                        {
                            Id = 42,
                            DesaKelurahanId = 14,
                            Nama = "Kompas"
                        },
                        new
                        {
                            Id = 43,
                            DesaKelurahanId = 15,
                            Nama = "Lewe"
                        },
                        new
                        {
                            Id = 44,
                            DesaKelurahanId = 15,
                            Nama = "Watu Cie"
                        },
                        new
                        {
                            Id = 45,
                            DesaKelurahanId = 16,
                            Nama = "Pandang"
                        },
                        new
                        {
                            Id = 46,
                            DesaKelurahanId = 16,
                            Nama = "Pongkor"
                        },
                        new
                        {
                            Id = 47,
                            DesaKelurahanId = 17,
                            Nama = "Moncok"
                        });
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.StandarBeratMenurutBBTB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("integer");

                    b.Property<int>("KategoriUmur")
                        .HasColumnType("integer");

                    b.Property<double>("MedianBeratBadan")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus1")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus2")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus3")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus1")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus2")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus3")
                        .HasColumnType("double precision");

                    b.Property<double>("TinggiBadan")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TblStandarBeratMenurutBBTB");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.OrangTua", "OrangTua")
                        .WithMany("DaftarBalita")
                        .HasForeignKey("OrangTuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrangTua");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.DesaKelurahan", "DesaKelurahan")
                        .WithMany("DaftarOrangTua")
                        .HasForeignKey("DesaKelurahanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesaKelurahan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Pengecekan", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.Balita", "Balita")
                        .WithMany("DaftarPengecekan")
                        .HasForeignKey("BalitaNIK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatusGizi.Domain.Entities.Posyandu", "Posyandu")
                        .WithMany("DaftarPengecekan")
                        .HasForeignKey("PosyanduId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balita");

                    b.Navigation("Posyandu");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.DesaKelurahan", "DesaKelurahan")
                        .WithMany("DaftarPosyandu")
                        .HasForeignKey("DesaKelurahanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesaKelurahan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.Navigation("DaftarPengecekan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.DesaKelurahan", b =>
                {
                    b.Navigation("DaftarOrangTua");

                    b.Navigation("DaftarPosyandu");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.Navigation("DaftarBalita");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.Navigation("DaftarPengecekan");
                });
#pragma warning restore 612, 618
        }
    }
}
