// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StatusGizi.Infrastructure.Database;

#nullable disable

namespace StatusGizi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241123100136_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.Property<int>("NIK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NIK"));

                    b.Property<double>("BeratBadanWaktuLahir")
                        .HasColumnType("double precision");

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrangTuaNIK")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalLahir")
                        .HasColumnType("date");

                    b.Property<double>("TinggiBadanWaktuLahir")
                        .HasColumnType("double precision");

                    b.HasKey("NIK");

                    b.HasIndex("OrangTuaNIK");

                    b.ToTable("TblBalita");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.DesaKelurahan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblDesaKelurahan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.Property<int>("NIK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NIK"));

                    b.Property<int>("DesaKelurahanId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NIK");

                    b.HasIndex("DesaKelurahanId");

                    b.ToTable("TblOrangTua");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Pengecekan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BalitaNIK")
                        .HasColumnType("integer");

                    b.Property<double>("BeratBadan")
                        .HasColumnType("double precision");

                    b.Property<int>("KategoriGizi")
                        .HasColumnType("integer");

                    b.Property<double>("LingkarLenganAtas")
                        .HasColumnType("double precision");

                    b.Property<int>("PosyanduId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalPengecekan")
                        .HasColumnType("date");

                    b.Property<double>("TinggiBadan")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BalitaNIK");

                    b.HasIndex("PosyanduId");

                    b.ToTable("TblPengecekan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesaKelurahanId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DesaKelurahanId");

                    b.ToTable("TblPosyandu");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.StandarBeratMenurutBBTB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("integer");

                    b.Property<int>("KategoriUmur")
                        .HasColumnType("integer");

                    b.Property<double>("MedianBeratBadan")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus1")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus2")
                        .HasColumnType("double precision");

                    b.Property<double>("SDMinus3")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus1")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus2")
                        .HasColumnType("double precision");

                    b.Property<double>("SDPlus3")
                        .HasColumnType("double precision");

                    b.Property<double>("TinggiBadan")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TblStandarBeratMenurutBBTB");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.OrangTua", "OrangTua")
                        .WithMany("DaftarBalita")
                        .HasForeignKey("OrangTuaNIK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrangTua");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.DesaKelurahan", "DesaKelurahan")
                        .WithMany("DaftarOrangTua")
                        .HasForeignKey("DesaKelurahanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesaKelurahan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Pengecekan", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.Balita", "Balita")
                        .WithMany("DaftarPengecekan")
                        .HasForeignKey("BalitaNIK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatusGizi.Domain.Entities.Posyandu", "Posyandu")
                        .WithMany("DaftarPengecekan")
                        .HasForeignKey("PosyanduId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balita");

                    b.Navigation("Posyandu");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.HasOne("StatusGizi.Domain.Entities.DesaKelurahan", "DesaKelurahan")
                        .WithMany("DaftarPosyandu")
                        .HasForeignKey("DesaKelurahanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesaKelurahan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Balita", b =>
                {
                    b.Navigation("DaftarPengecekan");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.DesaKelurahan", b =>
                {
                    b.Navigation("DaftarOrangTua");

                    b.Navigation("DaftarPosyandu");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.OrangTua", b =>
                {
                    b.Navigation("DaftarBalita");
                });

            modelBuilder.Entity("StatusGizi.Domain.Entities.Posyandu", b =>
                {
                    b.Navigation("DaftarPengecekan");
                });
#pragma warning restore 612, 618
        }
    }
}
